"""Test functions of the CPU itself."""


ZERO_PAGE_LOCATION = 0x20
INDEX = 0x05
ABSOLUTE_LOCATION = 0x0101  # lower byte + index must be less than 255
PAGE_CROSS_ABSOLUTE_LOCATION = 0x0101
PAGE_CROSS_INDEX = 0xff
ZERO_PAGE_POINTER_LOCATION = 0x08
INDIRECT_DATA_LOCATION_ZERO_PAGE = 0x10
INDIRECT_DATA_LOCATION = 0x0110
TEST_VALUE = 0xfe
